name: "Ruby on Rails CI"

env:
  RUBY_VERSION: 3.1.2
  NODE_VERSION: 18.12.0
  BUNDLER_VERSION: 2.3.22
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  rails-workflow:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SQLite
        run: sudo apt-get install -y libsqlite3-dev
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Yarn Install
        run: yarn install
        
      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Set up asset pipeline
        run: | 
          yarn build
          yarn build:css

      - name: Run tests
        run: bin/rake
        
      - name: Run Rubocop
        run: bundle exec rubocop -c .rubocop.yml
        
      - name: Security Audit
        run: |
          gem install bundler-audit
          bundle-audit --update
